services:
  postgres:
    container_name: 'postgres'
    image: postgres:14
    env_file: '.env'
    ports:
      - '5432:5432'
    restart: always
    networks:
      - bridge
  back:
    container_name: 'back'
    image: test_tl_back:latest
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    env_file: '.env'
    restart: always
    networks:
      - bridge
  nginx:
    container_name: 'nginx'
    image: test_tl_nginx:latest
    build: ./nginx
    ports:
      - 80:80
    restart: always
    networks:
      - bridge

networks:
  bridge:
    driver: bridge